<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-M19LQA3N" failures="1" tests="5" name="abhiacademy.tests.SubmitOrderTest" time="33.114" errors="0" timestamp="2024-11-29T19:53:23 IST" skipped="1">
  <testcase classname="abhiacademy.tests.SubmitOrderTest" name="validateOrder" time="2.739">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at abhiacademy.pageobjects.MyOrderPage.checkOrderHisAndDel(MyOrderPage.java:48)
at abhiacademy.tests.SubmitOrderTest.validateOrder(SubmitOrderTest.java:62)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- validateOrder -->
  <testcase classname="abhiacademy.tests.SubmitOrderTest" name="validateOrder" time="4.717">
    <skipped/>
  </testcase> <!-- validateOrder -->
  <testcase classname="abhiacademy.tests.SubmitOrderTest" name="submitOrder" time="11.713"/>
  <testcase classname="abhiacademy.tests.SubmitOrderTest" name="validateOrder" time="3.214"/>
  <testcase classname="abhiacademy.tests.SubmitOrderTest" name="submitOrder" time="10.731"/>
</testsuite> <!-- abhiacademy.tests.SubmitOrderTest -->
